### ISSUE TITLE
Does not build anymore for me

### ISSUE THREAD

**Issue by nkiesel** [Rasbats/otcurrent_pi#15]
Hi,
I now get compile errors due to missing `PLUGIN_CATALOG_NAME`, `OCPN_API_VERSION_MAJOR`, `OCPN_API_VERSION_MINOR`.  What am I doing wrong?

**Comment by Rasbats** [comment]
nkiesel... What OS are you running? Suggest downloading a zip from the otcurrent-legacy branch and compiling with that. Making the managed version tarballs made things difficult to compile standalone. The code is the same in the two branches.

**Comment by nkiesel** [comment]
Debian unstable, OpenCPN and all plugins compiled from source code.  I'm trying to use the master branch.  perhaps that is the root cause for my problems?

**Comment by Rasbats** [comment]
Using Jon Gough's frontend2 template for compiling the managed plugin (master branch) has caused me a few problems if I compile standalone versions of the installer. Using CI works ok. You could set up your own Cloudsmith repos for this. The legacy branch should not cause a problem but you would have to uninstall the managed version, if present.

Alec Leamas has been working on the 'ShipDriver' plugin, in order to make a tarball independently of CI. You may want to test compiling the master branch of that plugin.

[https://github.com/Rasbats/shipdriver_pi](url)

**Comment by rgleason** [comment]
I believe your version is different than "jon's frontend2" as it has been modified some time ago. 

It would be best to update to the current version 1.0.139, on my repos as it has two recent changes needed for mingw. OR. Use the ship driver version.

**Comment by rgleason** [comment]
Also Jon is very  open to PR's that fix any such problem.  On windows the system works very smoothly, allowing local builds, easy testing via  Plugin Import, and good environment build and deployment. 

Only thing not available  right now is checksum's which are very new, but will be implemented in the near future.

BTW, lennart G has been using ubuntu and frontend2  v1.0.139 for gps-odometer with some success.

**Comment by Rasbats** [comment]
Now using the ShipDriver template. Closing.
