### ISSUE TITLE
Does not run on RPi

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/otcurrent_pi#16]
Fails to run ... libjsoncpp.so.1 ... No such file.

**Comment by Rasbats** [comment]
Started compiling tarballs on the Pi, installing CMake and wxWidgets. Without doing anything else the plugin v2.8 now runs ok.

**Comment by leamas** [comment]
IT's a question of using the bundled libjsoncpp rather than the system one.  Using the bundled (the one lin libs/) measn there is no runtime linkage to libjsoncpp.so. 

The problem is that by default, the system library is used if available. The following patch should fix it:

```
diff --git a/libs/jsoncpp/CMakeLists.txt b/libs/jsoncpp/CMakeLists.txt
index a10a377..5a2fbdc 100644
--- a/libs/jsoncpp/CMakeLists.txt
+++ b/libs/jsoncpp/CMakeLists.txt
@@ -5,7 +5,7 @@ endif ()
 cmake_minimum_required(VERSION 3.1.0)
 project("jsoncpp")
 
-option(USE_SYSTEM_JSONCPP "Use system copy of library if available" ON)
+option(USE_SYSTEM_JSONCPP "Use system copy of library if available" OFF)
 
 add_library(_JSONCPP INTERFACE)
 add_library(ocpn::jsoncpp ALIAS _JSONCPP)

```

This should make it work as it should also of  libjsoncpp is available system-wide.

**Comment by Rasbats** [comment]
Now in master code. Closing.
